#!/usr/bin/env bash

# Me cambio al directorio del usuario cubie
export HOME=/home/cubie
cd $HOME

# Activo el virtualenv
source mopidy/bin/activate

# Ejecuto mopidy
exec chpst -u cubie:audio mopidy/bin/mopidy 2>&1
